#!/usr/bin/env bash

input_directory="/path/to/your/input_directory"

for input_file in "$@"; do
    echo "File: $input_file"
    ffprobe -v error -select_streams v:0 -show_entries stream=codec_name,codec_type,codec_long_name,width,height,bit_rate,avg_frame_rate -of default=noprint_wrappers=1 "$input_file"
    echo "---------------------------"
done

